<?php



 ?>


 <!DOCTYPE html>
 <html lang="en" dir="ltr">
   <head>
     <meta charset="utf-8">
     <title></title>
   </head>
   <body>
     <label class="label input"   for = "" >
     <select name="country" >

       <option value="ae">Emiratos Árabes</option>
       <option value="af">af  –  Afganistán</option>
       <option value="ai">ai  –  Anguila</option>
       <option value="al">al  –  Albania</option>
       <option value="am">am  –  Armenia</option>
       <option value="ao">ao  –  Angola</option>
       <option value="aq">aq  –  Antártida</option>
       <option value="ar">ar  –  Argentina</option>
       <option value="as">as  –  Samoa Americana</option>
       <option value="at">at  –  Austria</option>
       <option value="au">au  –  Australia</option>
       <option value="aw">aw  –  Aruba</option>
       <option value="az">az  –  Azerbaiyán</option>
       <option value="ba">ba  –  Bosnia-Herzegovina</option>
       <option value="bb">bb  –  Barbados</option>
       <option value="bd">bd  –  Bangladés</option>
       <option value="be">be  –  Bélgica</option>
       <option value="bf">bf  –  Burkina Faso</option>
       <option value="bg">bg  –  Bulgaria</option>
       <option value="bh">bh  –  Bahréin</option>
       <option value="bi">bi  –  Burundi</option>
       <option value="bj">bj  –  Benín</option>
       <option value="BL">BL - San Bartolomé</option>
       <option value="bm">bm  –  Bermudas</option>
       <option value="BN">BN - Brunei</option>
       <option value="bo">bo  –  Bolivia</option>
       <option value="ag">ag  –  Antigua y Barbuda</option>
       <option value="br">br  –  Brasil</option>
       <option value="BS">BS - Las Bahamas</option>
       <option value="bt">bt  –  Bután</option>
       <option value="bv">bv  –  Isla Bouvet</option>
       <option value="bw">bw  –  Botsuana</option>
       <option value="by">by  –  Bielorrusia</option>
       <option value="bz">bz  –  Belice</option>
       <option value="ca">ca  –  Canadá</option>
       <option value="cc">cc  –  Islas Cocos (Keeling)</option>
       <option value="cd">cd  –  Congo, República
       Democrática del congo </option>
       <option value="cf">cf  –  República Centroafricana</option>
       <option value="cg">cg  –  Congo, República del</option>
       <option value="ch">ch  –  Suiza</option>
       <option value="ci">ci  –  Costa de Marfil</option>
       <option value="ck">ck  –  Islas Cook</option>
       <option value="cl">cl  –  Chile</option>
       <option value="cm">cm  –  Camerún</option>
       <option value="cn">cn  –  China</option>
       <option value="co">co  –  Colombia</option>
       <option value="cr">cr  –  Costa Rica</option>
       <option value="cu">cu  –  Cuba</option>
       <option value="cv">cv  –  Cabo Verde</option>
       <option value="cw">CW - Curacao</option>
       <option value="cx">cx  –  Isla de Navidad</option>
       <option value="cy">cy  –  Chipre</option>
       <option value="cz">cz  –  República Checa</option>
       <option value="de">de  –  Alemania</option>
       <option value="dj">dj  –  Yibuti</option>
       <option value="dk">dk  –  Dinamarca</option>
       <option value="dm">dm  –  Dominica</option>
       <option value="do">do  –  República Dominicana</option>
       <option value="dz">dz  –  Argelia</option>
       <option value="ec">ec  –  Ecuador</option>
       <option value="ee">ee  –  Estonia</option>
       <option value="eg">eg  –  Egipto</option>
       <option value="eh">eh  –  Sahara Occidental</option>
       <option value="er">er  –  Eritrea</option>
       <option value="es">es  –  España</option>
       <option value="et">et  –  Etiopía</option>
       <option value="fi">fi  –  Finlandia</option>
       <option value="fj">fj  –  Fiyi</option>
       <option value="fk">fk  –  Islas Malvinas (Falkland)</option>
       <option value="fm">fm  –  Micronesia, Estados Federados de</option>
       <option value="fo">fo  –  Islas Feroe</option>
       <option value="fr">fr  –  Francia </option>
       <option value="FX">FX - Francia, metropolitana</option>
       <option value="ga">ga  –  Gabón</option>
       <option value="gb">gb  –  Reino Unido</option>
       <option value="gd">gd  –  Granada</option>
       <option value="ge">ge  –  Georgia</option>
       <option value="gf">gf  –  Guayana Francesa</option>
       <option value="gg">gg  –  Guernsey</option>
       <option value="gh">gh  –  Ghana</option>
       <option value="gi">gi  –  Gibraltar</option>
       <option value="gl">gl  –  Groenlandia</option>
       <option value="GM">GM - Gambia</option>
       <option value="gn">gn  –  Guinea</option>
       <option value="gp">gp  –  Guadalupe</option>
       <option value="gq">gq  –  Guinea Ecuatorial</option>
       <option value="gr">gr  –  Grecia</option>
       <option value="gs">gs  –  Islas Georgia del Sur y Sándwich del Sur</option>
       <option value="gt">gt  –  Guatemala</option>
       <option value="gu">gu  –  Guam</option>
       <option value="gw">gw  –  Guinea-Bissau</option>
       <option value="gy">gy  –  Guyana</option>
       <option value="hk">hk  –  Hong Kong</option>
       <option value="hm">hm  –  Islas Heard y McDonald</option>
       <option value="hn">hn  –  Honduras</option>
       <option value="HR">HR - Croacia</option>
       <option value="ht">ht  –  Haití</option>
       <option value="hu">hu  –  Hungría</option>
       <option value="id">id  –  Indonesia</option>
       <option value="ie">ie  –  Irlanda</option>
       <option value="il">il  –  Israel</option>
       <option value="im">im  –  Isla de Man</option>
       <option value="in">in  –  India</option>
       <option value="io">io  –  Territorio británico del océano Índico</option>
       <option value="iq">iq  –  Iraq</option>
       <option value="IR">IR - Irán</option>
       <option value="is">is  –  Islandia</option>
       <option value="it">it  –  Italia</option>
       <option value="je">je  –  Jersey</option>
       <option value="jm">jm  –  Jamaica</option>
       <option value="jo">jo  –  Jordania</option>
       <option value="jp">jp  –  Japón</option>
       <option value="ke">ke  –  Kenia</option>
       <option value="kg">kg  –  Kirguistán</option>
       <option value="kh">kh  –  Camboya</option>
       <option value="ki">ki  –  Kiribati</option>
       <option value="km">km  –  Comoras</option>
       <option value="kn">kn  –  San Cristóbal y Nieves</option>
       <option value="KP">KP - Corea del Norte</option>
       <option value="KR">KR - Corea del Sur</option>
       <option value="kw">kw  –  Kuwait</option>
       <option value="ky">ky  –  Islas Caimán</option>
       <option value="kz">kz  –  Kazajistán</option>
       <option value="LA">LA - Laos</option>
       <option value="lb">lb  –  Líbano</option>
       <option value="lc">lc  –  Santa Lucía</option>
       <option value="li">li  –  Liechtenstein</option>
       <option value="lk">lk  –  Sri Lanka</option>
       <option value="lr">lr  –  Liberia</option>
       <option value="ls">ls  –  Lesoto</option>
       <option value="lt">lt  –  Lituania</option>
       <option value="lu">lu  –  Luxemburgo</option>
       <option value="lv">lv  –  Letonia</option>
       <option value="LY">LY - Libia</option>
       <option value="ma">ma  –  Marruecos</option>
       <option value="mc">mc  –  Mónaco</option>
       <option value="MD">MD - Moldovia</option>
       <option value="me">me  –  Montenegro</option>
       <option value="MF">MF - Saint Martin</option>
       <option value="mg">mg  –  Madagascar</option>
       <option value="mh">mh  –  Islas Marshall</option>
       <option value="MK">MK - Macedonia</option>
       <option value="ml">ml  –  Mali</option>
       <option value="MM">MM - Burma</option>
       <option value="mn">mn  –  Mongolia</option>
       <option value="mo">mo  –  Macao</option>
       <option value="mp">mp  –  Islas Marianas del Norte</option>
       <option value="mq">mq  –  Martinica</option>
       <option value="mr">mr  –  Mauritania</option>
       <option value="ms">ms  –  Montserrat</option>
       <option value="mt">mt  –  Malta</option>
       <option value="mu">mu  –  Mauricio</option>
       <option value="mv">mv  –  Maldivas</option>
       <option value="mw">mw  –  Malaui</option>
       <option value="mx">mx  –  México</option>
       <option value="my">my  –  Malasia</option>
       <option value="mz">mz  –  Mozambique</option>
       <option value="na">na  –  Namibia</option>
       <option value="nc">nc  –  Nueva Caledonia</option>
       <option value="ne">ne  –  Níger</option>
       <option value="nf">nf  –  Isla Norfolk</option>
       <option value="ng">ng  –  Nigeria</option>
       <option value="ni">ni  –  Nicaragua</option>
       <option value="nl">nl  –  Países Bajos</option>
       <option value="no">no  –  Noruega</option>
       <option value="np">np  –  Nepal</option>
       <option value="nr">nr  –  Nauru</option>
       <option value="nu">nu  –  Niue</option>
       <option value="nz">nz  –  Nueva Zelanda</option>
       <option value="om">om  –  Omán</option>
       <option value="pa">pa  –  Panamá</option>
       <option value="pe">pe  –  Perú</option>
       <option value="pf">pf  –  Polinesia Francesa</option>
       <option value="pg">pg  –  Papúa Nueva Guinea</option>
       <option value="ph">ph  –  Filipinas</option>
       <option value="pk">pk  –  Pakistán</option>
       <option value="pl">pl  –  Polonia</option>
       <option value="pm">pm  –  San Pedro y Miguelón</option>
       <option value="pn">pn  –  Islas Pitcairn</option>
       <option value="pr">pr  –  Puerto Rico</option>
       <option value="PS">PS - Franja de Gaza</option>
       <option value="PS">PS - Cisjordania</option>
       <option value="pt">pt  –  Portugal</option>
       <option value="pw">pw  –  Palaos</option>
       <option value="py">py  –  Paraguay</option>
       <option value="qa">qa  –  Qatar</option>
       <option value="RE">RE - Reunion</option>
       <option value="ro">ro  –  Rumania</option>
       <option value="rs">rs  –  Serbia</option>
       <option value="RU">RU - Rusia</option>
       <option value="rw">rw  –  Ruanda</option>
       <option value="sa">sa  –  Arabia Saudita</option>
       <option value="sb">sb  –  Islas Salomón</option>
       <option value="sc">sc  –  Seychelles</option>
       <option value="sd">sd  –  Sudán</option>
       <option value="se">se  –  Suecia</option>
       <option value="sg">sg  –  Singapur</option>
       <option value="SH">SH - Santa Helena, Ascensión y Tristán de Acuña</option>
       <option value="si">si  –  Eslovenia</option>
       <option value="SJ">SJ - Svalbard</option>
       <option value="SK">SK - Eslovaquia</option>
       <option value="sl">sl  –  Sierra Leona</option>
       <option value="sm">sm  –  San Marino</option>
       <option value="sn">sn  –  Senegal</option>
       <option value="so">so  –  Somalia</option>
       <option value="sr">sr  –  Surinam</option>
       <option value="SS">SS - Sudán Sur</option>
       <option value="st">st  –  Santo Tomé y Príncipe</option>
       <option value="sv">sv  –  El Salvador</option>
       <option value="SX">SX - Sint Maarten</option>
       <option value="SY">SY - Siria</option>
       <option value="sz">sz  –  Suazilandia</option>
       <option value="tc">tc  –  Islas Turcas y Caicos</option>
       <option value="td">td  –  Chad/option>
       <option value="TF">TF - Territorios Australes Franceses</option>
       <option value="tg">tg  –  Togo</option>
       <option value="th">th  –  Tailandia</option>
       <option value="tj">tj  –  Tayikistán</option>
       <option value="tk">tk  –  Tokelau</option>
       <option value="tl">tl –  Timor Leste</option>
       <option value="tm">tm  –  Turkmenistán</option>
       <option value="tn">tn  –  Túnez</option>
       <option value="to">to  –  Tonga</option>
       <option value="tr">tr  –  Turquía</option>
       <option value="tt">tt  –  Trinidad y Tobago</option>
       <option value="tv">tv  –  Tuvalu</option>
       <option value="tw">tw  –  Taiwán</option>
       <option value="tz">tz  –  Tanzania</option>
       <option value="ua">ua  –  Ucrania</option>
       <option value="ug">ug  –  Uganda</option>
       <option value="um">um  –  Islas Ultramarinas menores de Estados Unidos</option>
       <option value="us">us  –  Estados Unidos</option>
       <option value="uy">uy  –  Uruguay</option>
       <option value="uz">uz  –  Uzbekistán</option>
       <option value="va">va  –  Santa Sede (Estado de la Ciudad del Vaticano)</option>
       <option value="vc">vc  –  San Vicente y las Granadinas</option>
       <option value="ve">ve  –  Venezuela</option>
       <option value="vg">vg  –  Islas Vírgenes Británicas</option>
       <option value="vi">vi  –  Islas Vírgenes de los EE. UU.</option>
       <option value="vn">vn  –  Vietnam</option>
       <option value="vu">vu  –  Vanuatu</option>
       <option value="wf">wf  –  Islas Wallis y Futuna</option>
       <option value="ws">ws  –  Samoa</option>
       <option value="XK">XK - Kosovo</option>
       <option value="ye">ye  –  Yemen</option>
       <option value="yt">yt  –  Mayotte</option>
       <option value="za">za  –  Sudáfrica</option>
       <option value="ZA">ZW - Zimbabwe</option>
       <option value="zm">zm  –  Zambia</option>
     </label> 
   </body>
 </html>
